### ISSUE TITLE
Does this plugin only work on amd motherboards?

### ISSUE THREAD

**Issue by howxcheng** [Mourdraug/FanControl.AsusWMI#2]
it doesn't work on my  rog Z690-A,I copied the dll file to the Plugins folder and restart,but showing "no plugin loaded" in software
![屏幕截图 2022-09-13 214811](https://user-images.githubusercontent.com/47664542/189918952-454d9f64-93d0-469a-a248-b1940157702c.png)

**Comment by Mourdraug** [comment]
It should not be dependent on the mobo socket. It looks like FanControl is not loading the plugin at all, if that was a problem with the board it would still load the plugin. Check if you can load any other plugin first.

**Comment by howxcheng** [comment]
HWInfo works normally
![屏幕截图 2022-09-13 214811](https://user-images.githubusercontent.com/47664542/189923105-dea52368-2433-49ab-a60b-017f5881a167.png)

**Comment by howxcheng** [comment]
I can't find ASUSHW class .does this mean that the plugin doesn't work on my motherboard
![屏幕截图 2022-09-13 214811](https://user-images.githubusercontent.com/47664542/189924816-a04da4af-37b9-4df4-8f02-83e0d06c08ec.png)

**Comment by howxcheng** [comment]
good news, I found it, bad news, it doesn't work

![屏幕截图 2022-09-13 214811](https://user-images.githubusercontent.com/47664542/189930843-3c5ccf2a-5db6-458e-86e1-23bf80af372b.png)

log >> 
2022/9/13 22:33:23: AsusWMIPlugin Initialization failed.
2022/9/13 22:33:24: System.NullReferenceException: Object reference not set to an instance of an object.
   在 FanControl.AsusWMI.AsusWMIPlugin.Close()
   在 System.Collections.Generic.List`1.ForEach(Action`1 action)
   在 FanControl.Domain.ComputerAccessLayer.Close()
   在 FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
2022/9/13 22:33:24: Initialization failed.
